routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', 'HomeController@index'
);

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('orders.invoices','InvoiceController');        
        Route::resource('/orders', 'OrderController');
        Route::get('/report/customer', 'ReportController@customer')->name('reports.customer');
        Route::get('/report/facility', 'ReportController@facility')->name('reports.facility');
        Route::get('/pint/folio', 'FolioController@print')->name('folios.print');
        Route::resource('/reports','ReportController');
        Route::resource('/invoices', 'InvoiceController');

        Route::resource('/customers', 'CustomerController');
        Route::resource('/customer_types', 'CustomerTypeController');
        Route::resource('/users', 'UserController');
        Route::resource('/galleries', 'GalleryController');
        Route::resource('/facility_attributes', 'FacilityAttributeController');
        Route::resource('/addons', 'AddonController');
        Route::resource('/facility_details', 'FacilityDetailController');
        Route::resource('/facilities', 'FacilityController');
        Route::resource('/facility_types', 'FacilityTypeController');
        Route::resource('/custom_schedules', 'CustomScheduleController');
        Route::resource('/units', 'UnitController');
        Route::resource('/facilities.galleries', 'FacilityGalleryController');
        Route::resource('/facilities.facility_details', 'FacilityFacilityDetailController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/news', 'NewsController');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/banners', 'BannerController');
        Route::resource('/testimonies', 'TestimonyController');
        Route::resource('/custom_prices', 'CustomPriceController');
        Route::resource('/education_tours', 'EducationTourController');
        Route::resource('/education_tours.galleries', 'EducationTourGalleryController');
        Route::resource('/bundles.galleries', 'BundleGalleryController');
        Route::resource('/facilities.detail_facilities', 'FacilityDetailFacilityController');
        Route::resource('/facilities.custom_prices', 'FacilityCustomPriceController');
        Route::resource('/bundles', 'BundleController');
        Route::resource('/detail_facilities.custom_schedules', 'DetailFacilityCustomScheduleController');
    
        Route::get('/news_image/{news}', 'NewsController@editImage')->name('news.editImage');
        Route::put('/news_image/{news}', 'NewsController@updateImage')->name('news.updateImage');
        Route::get('/order/{order}/folios', 'OrderController@folio')->name('orders.folios.index');
    
        Route::resource('/bundlings', 'BundlingController');
        Route::resource('/bundlings.facilities', 'BundlingFacilityController');
        Route::resource('/folios', 'FolioController');
        Route::resource('/special_prices', 'SpecialPriceController');
        Route::resource('orders.order_documents','OrderDocumentController');
    }
);
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');


Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/order/{id}/invoices/create/{invoice]', 'InvoiceController@create')->name('order.invoice.create.ord');
Route::post('/order/stat','OrderController@stat')->name("orders.stat");

app/Http/Controllers/CustomerTypeController.php
<?php

namespace App\Http\Controllers;
use App\CustomerType;
use Illuminate\Http\Request;

class CustomerTypeController extends Controller
{
     //api
    public function get(Request $request)
    {
        $cus = CustomerType::where("name", "LIKE", "%".$request->q."%")->pluck('name', 'id');
        return $cus;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $customer_type = CustomerType::query();
        
        $filter = [];
        if(isset($request->filter)) {
            $filter = $request->filter;
            foreach ($filter as $key => $value) {
                if(!empty($value)) {
                    $customer_type = $customer_type->where($key, 'like', '%'.$value.'%');
                }
            }
        }
        
        $customer_type = $customer_type->paginate(10);
        return view('customer_types.index', compact('customer_type', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customer_type = new CustomerType;
        return view('customer_types.create', compact('customer_type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $customer_type = new CustomerType;
        $customer_type->fill($request->all());
        $customer_type->save();
        $request->session()->flash('toast', 'Tipe Cutomer berhasil ditambahkan');
        return redirect('/customer_types');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(CustomerType $customer_type)
    {
        return view('customer_types.create', compact('customer_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, CustomerType $customer_type)
    {
        $customer_type->fill($request->all());
        $customer_type->save();
        $request->session()->flash('toast', 'Tipe Customer berhasil diubah');
        return redirect('/customer_types');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(CustomerType $customer_type, Request $request)
    {
        try {
            $customer_type->delete();
            $request->session()->flash('toast', 'Tipe Customer berhasil dihapus!');
        } catch(\Illuminate\Database\QueryException $ex){ 
            $request->session()->flash('toast', 'Tipe Customer gagal dihapus. ' . substr($ex->getMessage(), 0, 15));
        }
        
        return redirect('/customer_types');
    }
}

resources/views/customer_types/create.blade.php
@extends('layouts.app')

@section('title')
{{ $customer_type->exists ? 'Ubah' : 'Tambah' }} Tipe
@endsection
@if($customer_type->exists)
@section('actionbtn')
<a data-href="{{ route('customer_types.destroy', $customer_type->id) }}" class="btn btn-danger destroy">Hapus Tipe</a>
@endsection
@endif
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("customer_types.index")}}'><i class='fa fa-cube'></i> Tipe Pelanggan</a></li>
<li><a href='#' class='active'>{{ $customer_type->exists ? 'Ubah' : 'Tambah'}} Tipe Pelanggan</a></li>
@endsection
@section('content')

<section class="form-candidate">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <!-- /.box-header -->
        <!-- form start -->
        @if($customer_type->exists)
        {!! Form::model($customer_type, ['route' => ['customer_types.update', $customer_type->id], 'method'=>'PATCH', 'role' => 'form']) !!}
        @else
        {!! Form::model($customer_type, ['route' => ['customer_types.store'], 'method'=>'POST', 'role' => 'form']) !!}
        @endif
        <div class="box-body">
          <div class="row">
            <div class="form-group col-md-12">
              <label>Nama</label>
              {!! Form::text('name', $customer_type->name, ['class'=> 'form-control','required' => 'required']) !!}
            </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
      </form>
    </div>
  </div>
</div>
</section>
@endsection
@include('layouts._deletebtn')

resources/views/customer_types/index.blade.php
@extends('layouts.app')

@section('title')
Manage Tipe Pelanggan
@endsection
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='#' class='active'><i class='fa fa-cube'></i> Tipe Pelanggan</a></li>
@endsection
@section('content')

<div class="row">
	<!-- Search User -->
	<form method="get" id="search-form">
		<div class="col-md-3">
			<div class="input-group no-border">
				<input type="text" class="form-control column-filter" name="filter[name]" placeholder="Nama" value="{{ !empty($filter['name']) ? $filter['name'] : '' }}"/>
				<span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
			</div>
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-primary btn-block">Cari</button>
		</div>
	</form>
</div>
<br>
<div class="box">
	<div class="box-header">
		<div class="row">
			<div class="col-md-3">
				<a href="{{ route('customer_types.create')}}" class="btn btn-success btn-block">Tambah Tipe &nbsp;<span class="fa fa-plus-circle"></span></a>
			</div>
		</div>
	</div>
	
	<!-- /.box-header -->
	<div class="box-body">
		<table id="example1" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nama</th>
					<th>Edit</th>
				</tr>
			</thead>
			<tbody>
				@foreach($customer_type as $t)
				<tr>
					<td>{{$t->id}}</td>
					<td>{{$t->name}}</td>
					<td>
						<a href="{{route('customer_types.edit',$t->id)}}">
							<button class="btn btn-warning">
								Edit
							</button>
						</a>
					</td>
				</tr>
				@endforeach
				@if($customer_type->count() == 0)
					<tr>
					<td colspan="7"><center><em>Tidak Ada Data.</em></center></td>
					</tr>
				@endif
			</tbody>
		</table>
		@php
		$filters = [];
		foreach ($filter as $key => $value) {
			$filters['filter['. $key .']'] = $value;
		}
		@endphp
		{{ $customer_type->appends($filters)->links() }}
	</div>
</div>

@stop