routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', 'HomeController@index'
);

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('orders.invoices','InvoiceController');        
        Route::resource('/orders', 'OrderController');
        Route::get('/report/customer', 'ReportController@customer')->name('reports.customer');
        Route::get('/report/facility', 'ReportController@facility')->name('reports.facility');
        Route::get('/pint/folio', 'FolioController@print')->name('folios.print');
        Route::resource('/reports','ReportController');
        Route::resource('/invoices', 'InvoiceController');

        Route::resource('/customers', 'CustomerController');
        Route::resource('/customer_types', 'CustomerTypeController');
        Route::resource('/users', 'UserController');
        Route::resource('/galleries', 'GalleryController');
        Route::resource('/facility_attributes', 'FacilityAttributeController');
        Route::resource('/addons', 'AddonController');
        Route::resource('/facility_details', 'FacilityDetailController');
        Route::resource('/facilities', 'FacilityController');
        Route::resource('/facility_types', 'FacilityTypeController');
        Route::resource('/custom_schedules', 'CustomScheduleController');
        Route::resource('/units', 'UnitController');
        Route::resource('/facilities.galleries', 'FacilityGalleryController');
        Route::resource('/facilities.facility_details', 'FacilityFacilityDetailController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/news', 'NewsController');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/banners', 'BannerController');
        Route::resource('/testimonies', 'TestimonyController');
        Route::resource('/custom_prices', 'CustomPriceController');
        Route::resource('/education_tours', 'EducationTourController');
        Route::resource('/education_tours.galleries', 'EducationTourGalleryController');
        Route::resource('/bundles.galleries', 'BundleGalleryController');
        Route::resource('/facilities.detail_facilities', 'FacilityDetailFacilityController');
        Route::resource('/facilities.custom_prices', 'FacilityCustomPriceController');
        Route::resource('/bundles', 'BundleController');
        Route::resource('/detail_facilities.custom_schedules', 'DetailFacilityCustomScheduleController');
    
        Route::get('/news_image/{news}', 'NewsController@editImage')->name('news.editImage');
        Route::put('/news_image/{news}', 'NewsController@updateImage')->name('news.updateImage');
        Route::get('/order/{order}/folios', 'OrderController@folio')->name('orders.folios.index');
    
        Route::resource('/bundlings', 'BundlingController');
        Route::resource('/bundlings.facilities', 'BundlingFacilityController');
        Route::resource('/folios', 'FolioController');
        Route::resource('/special_prices', 'SpecialPriceController');
        Route::resource('orders.order_documents','OrderDocumentController');
    }
);
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');


Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/order/{id}/invoices/create/{invoice]', 'InvoiceController@create')->name('order.invoice.create.ord');
Route::post('/order/stat','OrderController@stat')->name("orders.stat");

app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Coupon;
use App\CouponFacility;
use App\CouponFacilityType;
use App\CouponCustomer;
use App\CouponCustomerType;
use App\DetailFacility;
use App\Addon;
use App\Customer;
use App\Facility;
use App\Bundle;
use App\FacilityType;
use App\CustomerType;
use Carbon\Carbon;
use Illuminate\Validation\ValidationException;
use DB;

class CouponController extends Controller
{
    public function index(Request $request)
    {
        $coupons = Coupon::query();
        $filter = [];
        if(isset($request->filter)) {
            $filter = $request->filter;
            foreach ($filter as $key => $value) {
                if(!empty($value)) {
                    if($key=="start") {
                        $coupons  = $coupons->whereDate("start",">=",$value);
                    }
                    else if($key=="expiry") {
                        $coupons  = $coupons->whereDate("expiry","<=",$value);
                    }
                    else{
                        $coupons  = $coupons->where($key, 'like', '%'.$value.'%');
                    }
                }
            }
        }
        $coupons=$coupons->paginate(30);
        return view('coupons.index')
        ->with('filter', $filter)
        ->with('coupons', $coupons);
    }
    public function create()
    {
        $coupon = new Coupon;
        return view('coupons._form')->with('coupon', $coupon);
    }
    public function store(Request $request)
    {
        DB::beginTransaction();  
        $errors=[];      
        $coupon = new Coupon;
        $coupon->fill($request->except('facility', 'ex_facil', 'ftype', 'ex_ftype', 'user', 'ex_user', 'role', 'ex_role'));
        if($coupon->min_spend > $coupon->max_spend){
            DB::rollBack();
            $errors=array_add($errors,"max_spend","Harga maksimum harus lebih besar dari harga minimum");            
            $errors=array_add($errors,"min_spend","Harga minimum harus lebih kecil dari harga maximum");            
        }
        $coupon->save();
        foreach ((array) $request->facility as $fac) {
            $fa = new CouponFacility;
            $fa->coupon_id=$coupon->id;
            $id = explode("-",$fac);
            if($id[0]=="F"){
                $facil= Facility::find($id[1]);
                $fa->facs_id=$facil->id;
                $fa->facs_type="App\\Facility";
            }
            else if($id[0]=="A"){
                $facil= Addon::find($id[1]);
                $fa->facs_id=$facil->id;
                $fa->facs_type="App\\Addon";                
            }
            else{
                 $facil= Bundle::find($id[1]);
                $fa->facs_id=$facil->id;
                $fa->facs_type="App\\Bundle";                
            }
           
            $fa->save();
        }
        foreach ((array) $request->ex_facil as $fac) {
            $fa = new CouponFacility;
            $fa->coupon_id=$coupon->id;
            $id = explode("-",$fac);
            if($id[0]=="F"){
                $facil= Facility::find($id[1]);
                $fa->facs_id=$facil->id;
                $fa->facs_type="App\\Facility";
            }
            else if($id[0]=="A"){
                $facil= Addon::find($id[1]);
                $fa->facs_id=$facil->id;
                $fa->facs_type="App\\Addon";                
            }
            else{
                 $facil= Bundle::find($id[1]);
                $fa->facs_id=$facil->id;
                $fa->facs_type="App\\Bundle";                
            }
           $check = CouponFacility::where("facs_type",$fa->facs_type)->where("facs_id",$fa->facs_id)->where("coupon_id",$fa->coupon_id)->get();
           if(count($check)>0){
             $errors=array_add($errors,"ex_facil","Fasilitas yang di include tidak bisa di exclude");                           
           }
           $fa->exclude = 1;
            $fa->save();
        }
        //coupon facility
        foreach ((array) $request->ftype as $fac) {
            $fa = new CouponFacilityType;
            $fa->coupon_id=$coupon->id;
            $fa->facility_type_id=$fac;
            $fa->save();
        }
        foreach ((array) $request->ex_ftype as $fac) {

            $fa = new CouponFacilityType;
            $fa->coupon_id=$coupon->id;
            $fa->facility_type_id=$fac;
            $check = CouponFacilityType::where("facility_type_id",$fa->facility_type_id)->where("coupon_id",$fa->coupon_id)->get();
            $fctye = FacilityType::find($fa->facility_type_id);
            $chk2 = CouponFacility::whereIn("facs_id",$fctye->facility->pluck("id"))->where("facs_type","LIKE","%Facility")->where("exclude","0")->count();
            if(count($check)>0){
                $errors=array_add($errors,"ex_ftype","Tipe Fasilitas yang di include tidak bisa di exclude");                           
            }
            if($chk2 >0){
                $errors=array_add($errors,"ex_ftype","Fasilitas yang di include memiliki Tipe Fasilitas yang akan diexclude");                                           
            }
            $fa->exclude = 1;
            $fa->save();
        }

        //coupon user
        foreach ((array) $request->user as $csr) {
            $fa = new CouponCustomer;
            $fa->coupon_id=$coupon->id;
            $fa->customer_id=$csr;
            $fa->save();
        }
        foreach ((array) $request->ex_user as $csr) {
            $fa = new CouponCustomer;
            $fa->coupon_id=$coupon->id;
            $fa->customer_id=$csr;
            $check = CouponCustomer::where("customer_id",$fa->customer_id)->where("coupon_id",$fa->coupon_id)->get();
            if(count($check)>0){
                $errors=array_add($errors,"ex_user","Pelanggan yang di include tidak bisa di exclude");                           
            }
            $fa->exclude = 1;
            $fa->save();
        }
        //coupon customer type
        foreach ((array) $request->role as $rl) {
            $role= new CouponCustomerType;
            $role->coupon_id=$coupon->id;
            $role->customer_type_id=$rl;
            $role->save();
        }
        //coupon customer type
        foreach ((array) $request->ex_role as $rl) {
            $role= new CouponCustomerType;
            $role->coupon_id=$coupon->id;
            $role->customer_type_id=$rl;
            $check = CouponCustomerType::where("customer_type_id",$role->customer_type_id)->where("coupon_id",$role->coupon_id)->get();
            $ctyp = CustomerType::find($rl);
            $check2 = CouponCustomer::whereIn("id",$ctyp->pluck("id"))->where("exclude",0)->count();
            
            if(count($check)>0){
                $errors=array_add($errors,"ex_role","Jenis Pelanggan yang di include tidak bisa di exclude");                           
            }
            if($check2>0){
                $errors=array_add($errors,"ex_role","Pelanggan yang di include memiliki jenis pelanggan yang di exclude");                                           
            }
            $role->exclude=1;
            $role->save();
        }

         if(count($errors)>0){
                DB::rollBack();
                throw ValidationException::withMessages($errors);
            }
        $request->session()->flash('toast', 'Kupon berhasil ditambahkan!');
        DB::commit();
        return redirect()->route('coupons.index');
    }
    public function edit($id)
    {
        $coupon = Coupon::find($id);
    
        return view('coupons._form')->with('coupon', $coupon);
    }
    public function update($id, Request $request)
    {
        $coupon = Coupon::find($id);
        $coupon->fill($request->all());
        $coupon->save();
        $request->session()->flash('toast', 'Kupon  berhasil diubah!');
        return redirect()->route('coupons.index');
    }
    public function show(Coupon $coupon)
    {
        return view('coupons.show')->with('coupon', $coupon);
    }
    public function destroy(Request $request, Coupon $coupon)
    {
        CouponCustomer::where("coupon_id",$coupon->id)->delete();
        CouponCustomerType::where("coupon_id",$coupon->id)->delete();
        CouponFacilityType::where("coupon_id",$coupon->id)->delete();
        CouponFacility::where("coupon_id",$coupon->id)->delete();
        $coupon->delete();
        $request->session()->flash('toast', 'Kupon berhasil dihapus!');
        $coupon->delete();
        return redirect()->route('coupons.index');
    }

    public function get(Request $req){
        $cup=Coupon::where("code", "LIKE", $req->coden)->first();
        if(sizeof($cup)<=0) {
            return json_encode(array("Tidak Ada Kupon Tersebut",0,0,0));            
        }
        if($cup->expiry->diffInDays(Carbon::now())>0 && $cup->expiry->isPast()) {
            return json_encode(array("Kupon Gagal digunakan! Kupon Sudah Expired",0,0,0));
        }
        if($cup->start->diffInDays(Carbon::now())>0 && $cup->start->isFuture()) {
            return json_encode(array("Kupon Gagal digunakan! Kupon Tidak Berlaku",0,0,0));
         }
        $cst = Customer::find($req->customer_id);        
        $cus = $cup->coupon_customer;
        $count=0;
        $match=0;
        foreach($cus as $cs){
            if($req->customer_id==$cs->customer_id && $cs->exclude==1){    
                return json_encode(array("Kupon Gagal digunakan! Customer ini tidak dapat menggunakan kupon ini",0,0,0));                                                                                                      
            }
            else if($req->customer_id==$cs->customer_id ){
                $match++;
            }
            if($cs->exclude==0){  
                $count++;  
            }
        }
        if($match!=$count){
            return json_encode(array("Kupon Gagal digunakan! Tidak Terdapat kupon untuk customer ini",0,0,0));                                 
            
        }
        
         $count=0;

resources/views/coupons/_form.blade.php
@extends('layouts.app')

@section('title')
{{ $coupon->exists ? 'Ubah' : 'Tambah' }} Kupon
@endsection
@if($coupon->exists)
@section('actionbtn')
<a data-href="{{ route('coupons.destroy', $coupon->id) }}" class="btn btn-danger destroy">Hapus Kupon</a>
@endsection
@endif

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("coupons.index")}}'><i class='fa fa-ticket'></i> Kupon</a></li>
<li><a href='#' class='active'>{{ $coupon->exists ? 'Ubah' : 'Tambah'}} Kupon</a></li>
@endsection
@section('content')
<div class="row">
<div class="col-xs-10">
<div class="box">
<div class="box-body">
@if($coupon->exists)
{!! Form::model($coupon, ['route' => ['coupons.update', $coupon->id], 'method'=>'PATCH', 'files' => true]) !!}
@else
{!! Form::model($coupon, ['route' => ['coupons.store'], 'class' => 'col s12', 'files' => true]) !!}
@endif

<div class="form-group">
{{ Form::label('code','Kode') }}
{{ Form::text('code', $coupon->code, ['class' => 'form-control', 'required']) }}
@if ($errors->has('code'))
<div class="help-block text-red">
{{ $errors->first('code') }}
</div>
@endif
</div>
<div class="form-group">
{{ Form::label('description','Deskripsi') }}
{{ Form::textarea('description', $coupon->description, [ 'class' => 'form-control']) }}
@if ($errors->has('description'))
<div class="help-block text-red">
{{ $errors->first('description') }}
</div>
@endif
</div>
<div class="form-group">
{{ Form::label('type','Tipe diskon') }}
{{ Form::select('type', array(1=> 'Diskon Persentase',2 => 'Diskon Fix') , $coupon->type, ['class' => 'form-control select2', 'required']) }}
@if ($errors->has('type'))
<div class="help-block text-red">
{{ $errors->first('type') }}
</div>
@endif

<div class="form-group">
{{ Form::label('amount','Nilai Kupon') }}
{{ Form::number('amount', $coupon->amount, ['min'=>0, 'class' => 'form-control', 'required']) }}
@if ($errors->has('amount'))
<div class="help-block text-red">
{{ $errors->first('amount') }}
</div>
@endif
</div>
<div class="form-group">
{{ Form::label('start','Tanggal Berlaku') }}
{{ Form::date('start', $coupon->start==null ? date('Y-m-d') : $coupon->start, ['class' => 'form-control', 'required']) }}
@if ($errors->has('start'))
<div class="help-block text-red">
{{ $errors->first('start') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('expiry','Tanggal Berakhir') }}
{{ Form::date('expiry', $coupon->expiry==null ? date('Y-m-d') : $coupon->expiry, ['class' => 'form-control', 'required']) }}
@if ($errors->has('expiry'))
<div class="help-block text-red">
{{ $errors->first('expiry') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('max_spend','Harga Maksimum') }}
{{ Form::number('max_spend', $coupon->max_spend, ['class' => 'form-control','min'=>0, 'value'=>0]) }}
@if ($errors->has('max_spend'))
<div class="help-block text-red">
{{ $errors->first('max_spend') }}
</div>
@endif
</div>
<div class="form-group">
{{ Form::label('min_spend','Harga Minimum') }}
{{ Form::number('min_spend', $coupon->min_spend, ['class' => 'form-control','min'=>0, 'value'=>0]) }}
@if ($errors->has('min_spend'))
<div class="help-block text-red">
{{ $errors->first('min_spend') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('indiv_use','Tidak Boleh digabung dengan kupon lain?') }}
{{ Form::checkbox('indiv_use',1,$coupon->indiv_use==null||$coupon->indiv_use==0 ? false:true) }}
@if ($errors->has('indiv_use'))
<div class="help-block text-red">
{{ $errors->first('indiv_use') }}
</div>
@endif
</div>
<div class="form-group">
{{ Form::label('exclude_sale','Hanya Boleh digunakan bila tidak ada barang diskon?') }}
{{ Form::checkbox('exclude_sale',1, $coupon->exclude_sale==null||$coupon->exclude_sale==0 ? false:true ) }}
@if ($errors->has('exclude_sale'))
<div class="help-block text-red">
{{ $errors->first('exclude_sale') }}
</div>
@endif
</div>
<div class="form-group">
{{ Form::label('facility','Fasilitas') }}
{{ Form::select('facility[]', array() ,old('facility') ? old('facility')  : $coupon->facility, ['class' => 'form-control fas','multiple']) }}
@if ($errors->has('facility'))
<div class="help-block text-red">
{{ $errors->first('facility') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('ex_facil','Kecuali Fasilitas') }}
{{ Form::select('ex_facil[]', array() , old('ex_facil') ? old('ex_facil')  : $coupon->ex_facil, ['class' => 'form-control fas','multiple']) }}
@if ($errors->has('ex_facil'))
<div class="help-block text-red">
{{ $errors->first('ex_facil') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('ftype','Tipe Fasilitas') }}
{{ Form::select('ftype[]', array() , old('ftype') ? old('ftype')  : $coupon->ftype, ['class' => 'form-control type','multiple']) }}
@if ($errors->has('ftype'))
<div class="help-block text-red">
{{ $errors->first('ftype') }}
</div>
@endif
</div>
<div class="form-group">
{{ Form::label('ex_ftype','Kecuali Tipe Fasilitas') }}
{{ Form::select('ex_ftype[]', array() , old('ex_ftype') ? old('ex_ftype')  : $coupon->ex_ftype, ['class' => 'form-control type','multiple']) }}
@if ($errors->has('ex_ftype'))
<div class="help-block text-red">
{{ $errors->first('ex_ftype') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('user','Pelanggan') }}
{{ Form::select('user[]', array() , old('user') ? old('user')  : $coupon->user, ['class' => 'form-control cus','multiple']) }}
@if ($errors->has('user'))
<div class="help-block text-red">
{{ $errors->first('user') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('ex_user','Kecuali Pengguna') }}
{{ Form::select('ex_user[]', array() ,  old('ex_user') ? old('ex_user')  :$coupon->ex_user, ['class' => 'form-control cus','multiple']) }}
@if ($errors->has('ex_user'))
<div class="help-block text-red">
{{ $errors->first('ex_user') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('role','Kelompok Pelanggan') }}
{{ Form::select('role[]', array() , old('role') ? old('role')  : $coupon->role, ['class' => 'form-control role','multiple']) }}
@if ($errors->has('role'))
<div class="help-block text-red">
{{ $errors->first('role') }}
</div>
@endif
</div>

<div class="form-group">
{{ Form::label('ex_role','Kecuali Kelompok Pelanggan') }}
{{ Form::select('ex_role[]', array() ,old('ex_role') ? old('ex_role')  : $coupon->ex_role, ['class' => 'form-control role','multiple']) }}
@if ($errors->has('ex_role'))
<div class="help-block text-red">
{{ $errors->first('ex_role') }}
</div>
@endif
</div>
       




</div>
<div class="box-footer">
{{ Form::submit('Simpan', ['class' => 'btn btn-success']) }}
</div>
{{ Form::close() }}
</div>
</div>
</div>
</div>
@endsection
@include('layouts._deletebtn')

@push('scripts')
<script type="text/javascript">
$(document).ready(function() {
    $(".select2").select2();

    $('.fas').select2({
    'width': '100%',
     placeholder: "Pilih Fasilitas", 
    ajax: {
    url: '{{ route('api.get.buyable')}}',
    dataType: 'json',
    delay: 250,
    processResults: function (data) {
    return {
    results:  $.map(data, function (item) {
    return {
    text: item.name,
    id: item.id
    }
    })
    };
    },
    cache: true
    }
    }); 
    $('.fas').trigger("change");

    $('.cus').select2({
    'width': '100%',
     placeholder: "Pilih Pelanggan", 
    ajax: {
    url: '{{ route('api.get.customer')}}',
    dataType: 'json',
    delay: 250,
    processResults: function (data) {
    return {
    results:  $.map(data, function (value, key) {
    return {
    text: value,
    id: key
    }
    })
    };
    },
    cache: true
    }
    });
    $('.cus').trigger("change");    

    $('.role').select2({
    'width': '100%',
     placeholder: "Pilih Kelompok Pengguna", 
    ajax: {
    url: '{{ route('api.get.customer_tpye')}}',
    dataType: 'json',
    delay: 250,
    processResults: function (data) {
    return {
    results:  $.map(data, function (value, key) {
    return {
    text: value,
    id: key
    }
    })
    };
    },
    cache: true
    }
    });
    $('.role').trigger("change");    
    

    $('.type').select2({
    'width': '100%',
     placeholder: "Tipe Fasilitas", 
    ajax: {
    url: '{{ route('api.get.facility_type')}}',
    dataType: 'json',
    delay: 250,
    processResults: function (data) {
    return {
    results:  $.map(data, function (value, key) {
    return {
    text: value,
    id: key
    }
    })
    };
    },
    cache: true
    }
    });
    $('.type').trigger("change");    
    
});
</script>
@endpush

resources/views/coupons/index.blade.php
@extends('layouts.app')
@section('title')
Manage Coupon
@endsection

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='#' class='active'><i class='fa fa-ticket'></i> Kupon</a></li>
@endsection
@section('content')
<style>
    input[type="date"]:before {
    content: attr(placeholder) !important;
    color: #aaa;
    margin-right: 0.5em;
    }
    input[type="date"]:focus:before,
    input[type="date"]:valid:before {
    content: "";
    }
</style>
<div class="row">
    <form method="get" id="search-form">
        <div class="col-md-3">
            <div class="input-group no-border">
                <input type="text" class="form-control column-filter" name="filter[code]" placeholder="kode" value="{{ !empty($filter['code']) ? $filter['code'] : '' }}" />
                <span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-group no-border">
                <input type="date" class="form-control column-filter" name="filter[start]" placeholder="start" value="{{ !empty($filter['start']) ? $filter['start'] : '' }}" />
                <span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
            </div>
        </div>
        <div class="col-md-3">
            <div class="input-group no-border">
                <input type="date" class="form-control column-filter" name="filter[expiry]" placeholder="expiry" value="{{ !empty($filter['expiry']) ? $filter['expiry'] : '' }}" />
                <span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
            </div>
        </div>
        <div class="col-md-3">
            <button type="submit" class="btn btn-primary btn-block">Cari</button>
        </div>
    </form>
</div>
<br>
<div class="row">
<div class="col-xs-12">
<div class="box box-primary">
<div class="box-header">
<a href="{{ route('coupons.create') }}"><button class="btn btn-primary"><span>  <i class="fa fa-plus"></i> </span>Tambah Coupon</button></a>
</div>
<div class="box-body">
<table id="example1" class="table table-bordered table-hover">
<thead>
<tr>
<th width="5%">No</th>
<th width="25%">kode</th>
<th width="25%">Tanggal Mulai</th>
<th width="25%">Tanggal Kadaluarsa</th>
<th width="25%">deskripsi</th>
<th width="25%" colspan="2">Action</th>
</tr>
</thead>
<tbody>
@foreach( $coupons as $key => $coupon )
<tr height="10">
<td>{{ $key+1 }}</td>
<td>{{ $coupon->code }}</td>
<td>{{ $coupon->startLabel }}</td>
<td>{{ $coupon->expiryLabel }}</td>
<td>{{ $coupon->description }}</td>
<td><a href="{{ route('coupons.edit',['id'=>$coupon->id]) }}" class="btn btn-warning btn-block">Edit</a></td>
<td><a href="{{ route('coupons.show',['id'=>$coupon->id]) }}" class="btn btn-primary btn-block">Show</span></a></td>

</tr>
@endforeach
@if($coupons->count() == 0)
<tr>
<td colspan="7"><center><em>Tidak Ada Data.</em></center></td>
</tr>
@endif
</tbody>
</table>
</div>
</div>
</div>
</div>
@endsection
@push('scripts')
<form id='destroy-form' method="POST">
{{ csrf_field() }}
<input type="hidden" name="_method" value="DELETE">
</form>
<script>
$(document).ready(function() {
$('.destroy').click(function() {
if(confirm('Apakah anda yakin?') ) {
$('#destroy-form').attr('action',$(this).data('href'));
$('#destroy-form').submit();
}
});
});
</script>
@endpush