routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', 'HomeController@index'
);

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('orders.invoices','InvoiceController');        
        Route::resource('/orders', 'OrderController');
        Route::get('/report/customer', 'ReportController@customer')->name('reports.customer');
        Route::get('/report/facility', 'ReportController@facility')->name('reports.facility');
        Route::get('/pint/folio', 'FolioController@print')->name('folios.print');
        Route::resource('/reports','ReportController');
        Route::resource('/invoices', 'InvoiceController');

        Route::resource('/customers', 'CustomerController');
        Route::resource('/customer_types', 'CustomerTypeController');
        Route::resource('/users', 'UserController');
        Route::resource('/galleries', 'GalleryController');
        Route::resource('/facility_attributes', 'FacilityAttributeController');
        Route::resource('/addons', 'AddonController');
        Route::resource('/facility_details', 'FacilityDetailController');
        Route::resource('/facilities', 'FacilityController');
        Route::resource('/facility_types', 'FacilityTypeController');
        Route::resource('/custom_schedules', 'CustomScheduleController');
        Route::resource('/units', 'UnitController');
        Route::resource('/facilities.galleries', 'FacilityGalleryController');
        Route::resource('/facilities.facility_details', 'FacilityFacilityDetailController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/news', 'NewsController');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/banners', 'BannerController');
        Route::resource('/testimonies', 'TestimonyController');
        Route::resource('/custom_prices', 'CustomPriceController');
        Route::resource('/education_tours', 'EducationTourController');
        Route::resource('/education_tours.galleries', 'EducationTourGalleryController');
        Route::resource('/bundles.galleries', 'BundleGalleryController');
        Route::resource('/facilities.detail_facilities', 'FacilityDetailFacilityController');
        Route::resource('/facilities.custom_prices', 'FacilityCustomPriceController');
        Route::resource('/bundles', 'BundleController');
        Route::resource('/detail_facilities.custom_schedules', 'DetailFacilityCustomScheduleController');
    
        Route::get('/news_image/{news}', 'NewsController@editImage')->name('news.editImage');
        Route::put('/news_image/{news}', 'NewsController@updateImage')->name('news.updateImage');
        Route::get('/order/{order}/folios', 'OrderController@folio')->name('orders.folios.index');
    
        Route::resource('/bundlings', 'BundlingController');
        Route::resource('/bundlings.facilities', 'BundlingFacilityController');
        Route::resource('/folios', 'FolioController');
        Route::resource('/special_prices', 'SpecialPriceController');
        Route::resource('orders.order_documents','OrderDocumentController');
    }
);
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');


Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/order/{id}/invoices/create/{invoice]', 'InvoiceController@create')->name('order.invoice.create.ord');
Route::post('/order/stat','OrderController@stat')->name("orders.stat");

app/SpecialPrice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SpecialPrice extends Model
{
    protected $guarded =[];

    public function Bundle()
    {
        return $this->morphTo();
    }
    public function Addon()
    {
        return $this->morphTo();
    }
    public function Facility()
    {
        return $this->morphTo();
    }
    public function customer_type()
    {
        return $this->BelongsTo('App\CustomerType');
    }

    public function getNameLabelAttribute()
    {
        $obj = Addon::find($this->special_id);
        if($this->special_type=="App\\Facility") {
            $obj=Facility::find($this->special_id);        
        }
        else if($this->special_type=="App\\Bundle"){
         $obj = Bundle::find($this->special_id);
        }
        return $obj->name;        
    }    
}

app/Http/Controllers/SpecialPriceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\SpecialPrice;
use App\CustomerType;
use App\Addon;
use App\Facility;
use App\Bundle;

class SpecialPriceController extends Controller
{
    public function index(Request $request){
        $special_prices = SpecialPrice::query();
        $filter = [];
        if(isset($request->filter)) {
            $filter = $request->filter;
            foreach ($filter as $key => $value) {
                if(!empty($value)) {
                    $special_prices  = $special_prices->where($key, 'like', '%'.$value.'%');
                }
            }
        }
        $special_prices=$special_prices->orderBy('id','DESC')->paginate(20);
        return view('special_price.index')->with('special_prices',$special_prices)->with('filter',$filter);
    }
    public function create(Request $req){
        
        $special_price = new SpecialPrice;
        $special_price->special_type = $req->u;
        $special_price->special_id = $req->id;        
        $cst = CustomerType::all()->pluck("name","id");
        $fac = Facility::pluck("name","id");                    
        if($req->u=="App\\Facility"){
            $fac = Facility::where("id",$req->id)->pluck("name","id");            
        }
        else if($req->u=="App\\Addon"){
            $fac = Addon::where("id",$req->id)->pluck("name","id");
        }
        else if($req->u=="App\\Bundle"){
            $fac = Bundle::where("id",$req->id)->pluck("name","id");            
        }
        return view('special_price._form')
        ->with('customer_types',$cst)
        ->with('facility',$fac)
        ->with('special_price',$special_price);
        
    }

    public function store(Request $request){
        // return $request;
        $special_price = new SpecialPrice;
        $special_price->fill($request->all());
        $special_price->save();
        $request->session()->flash('toast', 'Harga Spesial berhasil ditambahkan!');
        if($special_price->special_type=="App\\Facility"){
             return redirect()->route('facilities.show',$special_price->special_id);
        }
        else if($special_price->special_type=="App\\Addon"){
             return redirect()->route('addons.show',$special_price->special_id);                    
        }
        else if($special_price->special_type=="App\\Bundle"){
            return redirect()->route('bundles.show',$special_price->special_id);                    
        }
        return redirect()->route('special_prices.index');
    }
    public function edit($id){
        $special_price = SpecialPrice::find($id);
        return view('special_price._form')->with('special_price',$special_price);
    }
    public function update($id, Request $request){
        $special_price = SpecialPrice::find($id);
        $special_price->fill($request->all());
        $special_price->save();
        $request->session()->flash('toast', 'Harga Spesial  berhasil diubah!');
        return redirect()->route('special_prices.index');
    }
    public function show(SpecialPrice $special_price){
        return view('special_price.show')->with('special_price',$special_price);
    }
    public function destroy(Request $request, SpecialPrice $special_price){
        $special_price->delete();
        $request->session()->flash('toast', 'Harga Spesial berhasil dihapus!');
        $special_price->delete();
        return redirect()->route('special_prices.index');
    }
}

resources/views/special_price/_form.blade.php
@extends('layouts.app')
@section('title')
{{ $special_price->exists ? 'Ubah' : 'Tambah' }} Harga
@endsection
@if($special_price->exists)
@section('actionbtn')
<a data-href="{{ route('special_prices.destroy', $special_price->id) }}" class="btn btn-danger destroy">Hapus Harga</a>
@endsection
@endif

@if($special_price->special_type=="App\\Facility")
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("facilities.index")}}'><i class='fa fa-building'></i> Fasilitas</a></li>
<li><a href='{{ route("facilities.show",$special_price->special_id)}}'> {{ $facility[$special_price->special_id] }}</a></li>
<li><a href='#' class='active'>{{ $special_price->exists ? 'Ubah' : 'Tambah'}} Harga</a></li>
@endsection
@elseif($special_price->special_type=="App\\Addon")
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("addons.index")}}'><i class='fa fa-building'></i> Tambahan</a></li>
<li><a href='{{ route("addons.show",$special_price->special_id)}}'> {{ $facility[$special_price->special_id] }}</a></li>
<li><a href='#' class='active'>{{ $special_price->exists ? 'Ubah' : 'Tambah'}} Harga</a></li>
@endsection
@elseif($special_price->special_type=="App\\bundle")
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("bundles.index")}}'><i class='fa fa-star'></i> Paket</a></li>
<li><a href='{{ route("bundles.show",$special_price->special_id)}}'> {{ $facility[$special_price->special_id] }}</a></li>
<li><a href='#' class='active'>{{ $special_price->exists ? 'Ubah' : 'Tambah'}} Harga</a></li>
@endsection
@else
@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("special_prices.index")}}'><i class='fa fa-cube'></i> Harga</a></li>
<li><a href='#' class='active'>{{ $special_price->exists ? 'Ubah' : 'Tambah'}} Harga</a></li>
@endsection
@endif

@section('content')
<div class="row">
    <div class="col-xs-10">
        <div class="box">
            <div class="box-body">
                @if($special_price->exists)
                    {!! Form::model($special_price, ['route' => ['special_prices.update', $special_price->id], 'method'=>'PATCH', 'files' => true]) !!}
                @else
                    {!! Form::model($special_price, ['route' => ['special_prices.store'], 'class' => 'col s12', 'files' => true]) !!}
                @endif
                {{ Form::hidden('special_type', $special_price->special_type, ['class' => 'form-control', 'required']) }}                
                    <div class="form-group">
                        {{ Form::label('special_id','Item') }}
                        {{ Form::select('special_id',  empty($facility) ? array() : $facility , $special_price->special_id, ['class' => 'form-control select2 facs', 'required']) }}
                        @if ($errors->has('special_id'))
                            <div class="help-block text-red">
                                {{ $errors->first('special_id') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        {{ Form::label('customer_type_id','Tipe Pelanggan') }}
                        {{ Form::select('customer_type_id',empty($customer_types) ? array() : $customer_types , $special_price->customer_type_id, ['class' => 'form-control select2 custtype', 'required']) }}
                        @if ($errors->has('customer_type_id'))
                            <div class="help-block text-red">
                                {{ $errors->first('customer_type_id') }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group">
                        {{ Form::label('weekend_price','Harga Weekend Menginap') }}
                        {{ Form::number('weekend_price', $special_price->weekend_price, ['class' => 'form-control', 'required']) }}
                        @if ($errors->has('weekend_price'))
                            <div class="help-block text-red">
                                {{ $errors->first('weekend_price') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        {{ Form::label('price','Harga Weekday Menginap') }}
                        {{ Form::number('price', $special_price->price, ['class' => 'form-control', 'required']) }}
                        @if ($errors->has('price'))
                            <div class="help-block text-red">
                                {{ $errors->first('price') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        {{ Form::label('no_stay_weekend_price','Harga Weekend Tidak menginap') }}
                        {{ Form::number('no_stay_weekend_price', $special_price->no_stay_weekend_price, ['class' => 'form-control', 'required']) }}
                        @if ($errors->has('no_stay_weekend_price'))
                            <div class="help-block text-red">
                                {{ $errors->first('no_stay_weekend_price') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        {{ Form::label('no_stay_weekday_price','Harga weekday tidak menginap') }}
                        {{ Form::number('no_stay_weekday_price', $special_price->no_stay_weekday_price, ['class' => 'form-control', 'required']) }}
                        @if ($errors->has('no_stay_weekday_price'))
                            <div class="help-block text-red">
                                {{ $errors->first('no_stay_weekday_price') }}
                            </div>
                        @endif
                    </div>
                    
                    
                <div class="box-footer">
                    {{ Form::submit('Simpan', ['class' => 'btn btn-success']) }}
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $(".select2").select2();
    });
</script>
@endpush

resources/views/special_price/index.blade.php
@extends('layouts.app')
@section('title')
List Special Price
@endsection

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='#' class='active'><i class='fa fa-cube'></i> Special Price</a></li>
@endsection
@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <a href="{{ route('special_prices.create') }}"><button class="btn btn-primary"><span>  <i class="fa fa-plus"></i> </span>Tambah Special Price</button></a>
            </div>
            <div class="box-body">
                <table id="example1" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th rowspan="2" width="5%">No</th>
                            <th rowspan="2" width="15%">Nama</th>
                            <th rowspan="2" width="10%">Tipe Customer</th>
                            <th colspan="2" width="20%">Harga Menginap</th>
                            <th colspan="2" width="20%">Harga Tidak Menginap</th>
                            <th rowspan="2" width="10%" colspan="2">Action</th>
                        </tr>
                        <tr>
                             <th width="15%">Weekend Price</th>
                            <th width="15%">Weekday Price</th>
                            <th width="15%">Weekend Price</th>
                            <th width="15%">Weekday Price</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach( $special_prices as $key => $special_price )
                        <tr height="10">
                            <td>{{ $key+1 }}</td>
                            <td>{{ $special_price->nameLabel }}</td>
                            <td>{{ $special_price->typeLabel }}</td>
                            <td>{{ H::rupiah($special_price->weekend_price) }}</td>
                            <td>{{ H::rupiah($special_price->price) }}</td>
                            <td>{{ H::rupiah($special_price->no_stay_weekend_price) }}</td>
                            <td>{{ H::rupiah($special_price->no_stay_weekday_price) }}</td>
                            {{--  <td><a href="{{ route('special_prices.show',['id'=>$special_price->id]) }}"><i class="material-icons black-text">open_in_new</i></a>
                                <a href="{{ route('special_prices.edit',['id'=>$special_price->id]) }}">
                                    <i class="material-icons">mode_edit</i>
                                </a>
                                <i class="material-icons">delete</i>
                                <a class="destroy" data-href="{{ route('special_prices.destroy',['id'=>$special_price->id]) }}">
                                </a>
                            </td>  --}}
                        </tr>
                    @endforeach
                    @if($special_prices->count() == 0)
                        <tr>
                            <td colspan="7"><center><em>Tidak Ada Data.</em></center></td>
                        </tr>
                    @endif
                    </tbody>
            </table>
        </div>
        {{ $special_prices->links() }}
        </div>
    </div>
</div>
@endsection
@push('scripts')
<form id='destroy-form' method="POST">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="DELETE">
</form>
<script>
    $(document).ready(function() {
        $('.destroy').click(function() {
            if(confirm('Apakah anda yakin?') ) {
                $('#destroy-form').attr('action',$(this).data('href'));
                $('#destroy-form').submit();
            }
        });
    });
</script>
@endpush