routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get(
    '/', 'HomeController@index'
);

Route::Group(
    ['middleware'=>'auth'], function () {
        Route::resource('orders.invoices','InvoiceController');        
        Route::resource('/orders', 'OrderController');
        Route::get('/report/customer', 'ReportController@customer')->name('reports.customer');
        Route::get('/report/facility', 'ReportController@facility')->name('reports.facility');
        Route::get('/pint/folio', 'FolioController@print')->name('folios.print');
        Route::resource('/reports','ReportController');
        Route::resource('/invoices', 'InvoiceController');

        Route::resource('/customers', 'CustomerController');
        Route::resource('/customer_types', 'CustomerTypeController');
        Route::resource('/users', 'UserController');
        Route::resource('/galleries', 'GalleryController');
        Route::resource('/facility_attributes', 'FacilityAttributeController');
        Route::resource('/addons', 'AddonController');
        Route::resource('/facility_details', 'FacilityDetailController');
        Route::resource('/facilities', 'FacilityController');
        Route::resource('/facility_types', 'FacilityTypeController');
        Route::resource('/custom_schedules', 'CustomScheduleController');
        Route::resource('/units', 'UnitController');
        Route::resource('/facilities.galleries', 'FacilityGalleryController');
        Route::resource('/facilities.facility_details', 'FacilityFacilityDetailController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/news', 'NewsController');
        Route::resource('/categories', 'CategoryController');
        Route::resource('/banners', 'BannerController');
        Route::resource('/testimonies', 'TestimonyController');
        Route::resource('/custom_prices', 'CustomPriceController');
        Route::resource('/education_tours', 'EducationTourController');
        Route::resource('/education_tours.galleries', 'EducationTourGalleryController');
        Route::resource('/bundles.galleries', 'BundleGalleryController');
        Route::resource('/facilities.detail_facilities', 'FacilityDetailFacilityController');
        Route::resource('/facilities.custom_prices', 'FacilityCustomPriceController');
        Route::resource('/bundles', 'BundleController');
        Route::resource('/detail_facilities.custom_schedules', 'DetailFacilityCustomScheduleController');
    
        Route::get('/news_image/{news}', 'NewsController@editImage')->name('news.editImage');
        Route::put('/news_image/{news}', 'NewsController@updateImage')->name('news.updateImage');
        Route::get('/order/{order}/folios', 'OrderController@folio')->name('orders.folios.index');
    
        Route::resource('/bundlings', 'BundlingController');
        Route::resource('/bundlings.facilities', 'BundlingFacilityController');
        Route::resource('/folios', 'FolioController');
        Route::resource('/special_prices', 'SpecialPriceController');
        Route::resource('orders.order_documents','OrderDocumentController');
    }
);
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');


Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');
//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/order/{id}/invoices/create/{invoice]', 'InvoiceController@create')->name('order.invoice.create.ord');
Route::post('/order/stat','OrderController@stat')->name("orders.stat");

app/EducationTour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EducationTour extends Model
{
    protected $guarded=[];
    
    public function gallery()
    {
        return $this->morphMany('App\Gallery', 'galleriable');
    }
}

app/Http/Controllers/EducationTourController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\EducationTour;
use App\Gallery;
use Intervention\Image\ImageManagerStatic as Image;

class EducationTourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $education_tour = EducationTour::query();
        $filter = [];
        if(isset($request->filter)) {
            $filter = $request->filter;
            foreach ($filter as $key => $value) {
                if(!empty($value)) {
                    $education_tour = $education_tour->where($key, 'like', '%'.$value.'%');
                }
            }
        }
        

        $education_tour = $education_tour->paginate(10);
        return view('education_tours.index', compact('education_tour', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $education_tour = new EducationTour;
        return view('education_tours.create', compact('education_tour'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $input = $request->except(['images','files']);
        
        $educaton_tour = new EducationTour;
        $educaton_tour->fill($input);
        $educaton_tour->save();
        $educaton_tour->slug = str_slug($educaton_tour->id.'_'.$educaton_tour->title, '_');
        $dom = new \DomDocument();
        $dom->loadHtml($request->description);
        $images = $dom->getElementsByTagName('img');
        foreach($images as $img){
			$src = $img->getAttribute('src');
			
			// if the img source is 'data-url'
			if(preg_match('/data:image/', $src)){
				
				// get the mimetype
				preg_match('/data:image\/(?<mime>.*?)\;/', $src, $groups);
				$mimetype = $groups['mime'];
				
				// Generating a random filename
				$filename = uniqid();
				$filepath = "/image/$filename.$mimetype";
	
				// @see http://image.intervention.io/api/
				$image = Image::make($src)
				  // resize if required
				  /* ->resize(300, 200) */
				  ->encode($mimetype, 100) 	// encode file to the specified mimetype
				  ->save(public_path($filepath));
				
				$new_src = asset($filepath);
				$img->removeAttribute('src');
				$img->setAttribute('src', $new_src);
			} // <!--endif
        } // <!--endforeach
        
        $educaton_tour->description = $dom->saveHTML();

        // return $educaton_tour;
        $educaton_tour->save();
        $file = $request->file('images');
        foreach($file as $f){
            $filename = $f->getClientOriginalName();
            $path = public_path().'/image/';
            $f->move($path, $filename);
            
            $gallery = new Gallery;
            $gallery->image_path = $filename;
            $gallery->galleriable_id = $educaton_tour->id;
            $gallery->galleriable_type = 'EducationTour';            
            $gallery->save();
            $gallery->slug = str_slug($gallery->id.'_'.$gallery->image, '_');
            $gallery->save();
        }
        $request->session()->flash('toast', 'Eduwisata berhasil ditambahkan!');
        return redirect('/education_tours/'.$educaton_tour->id);      
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(EducationTour $education_tour)
    {

        $gallery = Gallery::query();
        $gallery = $gallery->where('galleriable_type', '=', 'EducationTour');
        $gallery = $gallery->where('galleriable_id', '=', $education_tour->id);
        $gallery = $gallery->paginate(5, ['*'], 'gallery');

        return view('education_tours.show', compact('education_tour', 'gallery'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(EducationTour $education_tour)
    {
        return view('education_tours.create', compact('education_tour'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, EducationTour $education_tour)
    {
        $education_tour->fill($request->all());
        $education_tour->slug = str_slug($education_tour->id.'_'.$education_tour->title, '_');
        $education_tour->save();
        $request->session()->flash('toast', 'Eduwisata berhasil diubah!');
        
        return redirect('/education_tours/'.$education_tour->id); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(EducationTour $education_tour, Request $request)
    {
        try {
            $education_tour->delete();
            $request->session()->flash('toast', 'Eduwisata berhasil dihapus!');
        } catch(\Illuminate\Database\QueryException $ex){ 
            $request->session()->flash('toast', 'Eduwisata gagal dihapus. ' . substr($ex->getMessage(), 0, 15));
        }
        
        return redirect('/education_tours');
    }
}

resources/views/education_tours/create.blade.php
@extends('layouts.app')

@section('title')
{{ $education_tour->exists ? 'Ubah' : 'Tambah' }} Eduwisata
@endsection
@if($education_tour->exists)
@section('actionbtn')
<a data-href="{{ route('education_tours.destroy', $education_tour->id) }}" class="btn btn-danger destroy">Hapus Eduwisata</a>
@endsection
@endif

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("education_tours.index")}}'><i class='fa fa-tree'></i> Eduwisata</a></li>
<li><a href='#' class='active'>{{ $education_tour->exists ? 'Ubah' : 'Tambah'}} Eduwisata</a></li>
@endsection
@section('content')

<section class="form-candidate">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <!-- /.box-header -->
        <!-- form start -->
        @if($education_tour->exists)
        {!! Form::model($education_tour, ['route' => ['education_tours.update', $education_tour->id], 'method'=>'PATCH','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
        @else
        {!! Form::model($education_tour, ['route' => ['education_tours.store'], 'method'=>'POST','enctype'=>'multipart/form-data', 'role' => 'form']) !!}
        @endif
        <div class="box-body">
          <div class="row">
            <div class="form-group col-md-12">
              <label>Judul</label>
              {!! Form::text('title', $education_tour->title, ['class'=> 'form-control','required' => 'required']) !!}
            </div>
            <div class="form-group col-md-12">
              <label>Deskripsi</label>
              {!! Form::textarea('description', $education_tour->description, ['id'=>'description','class'=> 'form-control','required' => 'required']) !!}
            </div>
            @if(!$education_tour->exists)
            <div class="col-md-12">
              <input type="file" class="form-control" id="images" name="images[]" onchange="preview_images();" multiple/>
            </div>
            <div class="col-md-12">
              <div class="row" id="image_preview"></div>
            </div>
            @endif
          </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Simpan</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
</section>
<!-- CK Editor -->

{{--  <script>
  $(function () {
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('description')
  })
</script>  --}}
@endsection
@include('layouts._deletebtn')
@push('scripts')
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script> 

{{--  <script src="{{asset('js/summernote.min.js')}}"></script>  --}}
<script>
  $("#description").summernote();
  function preview_images() 
  {
   var total_file=document.getElementById("images").files.length;
   for(var i=0;i<total_file;i++)
   {
    $('#image_preview').append("<div class='col-md-3' style='padding-top:20px'><img class='img-responsive' src='"+URL.createObjectURL(event.target.files[i])+"'></div>");
  }
}
</script>
@endpush

resources/views/education_tours/index.blade.php
@extends('layouts.app')

@section('title')
Manage Eduwisata
@endsection

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='#' class='active'><i class='fa fa-tree'></i> Education Tour</a></li>
@endsection

@section('content')

<div class="row">
	<!-- Search User -->
	<form method="get" id="search-form">
		<div class="col-md-3">
			<div class="input-group no-border">
				<input type="text" class="form-control column-filter" name="filter[title]" placeholder="Judul" value="{{ !empty($filter['title']) ? $filter['title'] : '' }}"/>
				<span class="input-group-addon icon-search"><i class="fa fa-search"></i></span>
			</div>
		</div>
		<div class="col-md-3">
			<button type="submit" class="btn btn-primary btn-block">Cari</button>
		</div>
	</form>
</div>
<br>
<div class="box">
	<div class="box-header">
		<div class="row">
			<div class="col-md-3">
				<a href="{{ route('education_tours.create')}}" class="btn btn-success btn-block">Tambah Eduwisata &nbsp;<span class="fa fa-plus-circle"></span></a>
			</div>
		</div>
	</div>
	
	<!-- /.box-header -->
	<div class="box-body">
		<table id="example1" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th>ID</th>
					<th>Judul</th>
					{{--  <th>Deskripsi</th>  --}}
					<th>Edit</th>
					<th>Show Detail</th>
				</tr>
			</thead>
			<tbody>
				@foreach($education_tour as $f)
				<tr>
					<td>{{$f->id}}</td>
					<td>{{$f->title}}</td>
					{{--  <td>{{$f->description}}</td>  --}}
					<td>
						<a href="{{route('education_tours.edit',$f->id)}}">
							<button class="btn btn-warning">
								Edit
							</button>
						</a>
					</td>
					<td>
						<a href="{{route('education_tours.show',$f->id)}}">
							<button class="btn btn-primary">
								Show
							</button>
						</a>
					</td>
				</tr>
				@endforeach
				@if($education_tour->count() == 0)
					<tr>
					<td colspan="7"><center><em>Tidak Ada Data.</em></center></td>
					</tr>
				@endif
			</tbody>
		</table>
		@php
		$filters = [];
		foreach ($filter as $key => $value) {
		$filters['filter['. $key .']'] = $value;
	}
	@endphp
	{{ $education_tour->appends($filters)->links() }}
</div>
</div>

@stop

resources/views/education_tours/show.blade.php
@extends('layouts.app')
@push('styles')
<link rel="stylesheet" type="text/css" href="{{asset('slick/slick.css')}}">
<link rel="stylesheet" type="text/css" href="{{asset('slick/slick-theme.css')}}">
<style>

	* {
		box-sizing: border-box;
	}


	.slick-slide {
		margin: 0px 25px;
	}

	.slick-slide img {
		width: 100%;
	}

	.slick-prev:before,
	.slick-next:before {
		color: black;
	}


	.slick-slide {
		transition: all ease-in-out .3s;
		opacity: .2;
	}
	.slick-slide:focus {
		opacity:1;
	}

	.slick-active {
		opacity: .5;
	}


	/* Main carousel style */
	.carousel {
		width: 600px;
	}

	/* Indicators list style */
	.article-slide .carousel-indicators {
		bottom: 0;
		left: 0;
		margin-left: 5px;
		width: 100%;
	}
	/* Indicators list style */
	.article-slide .carousel-indicators li {
		border: medium none;
		border-radius: 0;
		float: left;
		height: 54px;
		margin-bottom: 5px;
		margin-left: 0;
		margin-right: 5px !important;
		margin-top: 0;
		width: 100px;
	}
	/* Indicators images style */
	.article-slide .carousel-indicators img {
		border: 2px solid #FFFFFF;
		float: left;
		height: 54px;
		left: 0;
		width: 100px;
	}
	/* Indicators active image style */
	.article-slide .carousel-indicators .active img {
		border: 2px solid #428BCA;
		opacity: 0.7;
	}
</style>
@endpush
@section('title')
Manage Eduwisata
@endsection

@section('breadcrumb')
<li><a href='{{ route("home") }}'><i class='fa fa-dashboard'></i> Home</a></li>
<li><a href='{{ route("education_tours.index")}}'><i class='fa fa-tree'></i> Eduwisata</a></li>
<li><a href='#' class='active'>Detail Eduwisata</a></li>
@endsection
@section('content')
<div class="row">
	<section class="col-md-8">
		<div class="box">
			<div class="box-header">
				<div class="row">
					<div class="col-md-12">
						<h1>Nama: {{$education_tour->title}}</h1>
					</div>
				</div>
			</div>	
		</div>
	</section>
	<section class="col-md-12">
		<div class="box">
			
			<div class="box-header">
				<div class="row">
					<div class="col-md-3">
						Deskripsi
					</div>
				</div>
			</div>	
			<div class="box-body" >
				<div class="row">
					<h4>
						<div class="col-md-12">
							<div class="col-md-9">{!! $education_tour->description!!}</div>
						</div>
					</h4>
				</div>
			</div>
			<div class="box-footer">
				<div class="row">
					<div class="col-md-3 col-md-offset-9">
						<a href="{{ route('education_tours.edit',$education_tour->id)}}" class="btn btn-warning btn-block">Ubah Deskripsi &nbsp;<span class="fa fa-plus-circle"></span></a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="col-md-12">
		<div class="box">
			<div class="box-header">
				<div class="row">
					<div class="col-md-3">
						Gallery
					</div>

					<div class="col-md-3 pull-right">
						<a href="{{ route('education_tours.galleries.create',$education_tour->id)}}" class="btn btn-success btn-block">Tambah Detail Gallery &nbsp;<span class="fa fa-plus-circle"></span></a>
					</div>
				</div>
			</div>

			<!-- /.box-header -->
			<div class="box-body" style="height: 65vh;overflow-y:visible">
				<div class="row">
					<div class="col-md-7">
						<div class="carousel slide article-slide" id="article-photo-carousel">
							<!-- Wrapper for slides -->
							<div class="carousel-inner cont-slider">
								<div class="item" style="display:none">
								</div>
						@foreach($education_tour->gallery as $g)
						@if($loop->first)
						<div class="item active" >
							<img alt="" title="" style="width:600px;height:400px!important" src="{{asset('image/'.$g->image_path)}}">
						</div>
						@else
						<div class="item" >
							<img alt="" title="" style="width:600px;height:400px!important" src="{{asset('image/'.$g->image_path)}}">
						</div>
						@endif
						@endforeach
					</div>
					<!-- Indicators -->
					<ol class="carousel-indicators" >
						<section class="regular slider">
							@foreach($education_tour->gallery as $key => $g)
							<div data-slide-to={{$key+1}} data-target="#article-photo-carousel">
								<img alt="" src="{{asset('image/'.$g->image_path)}}">
							</div>
							@endforeach
						</section>
					</ol>
				</div>
			</div>
			<div class="col-md-5" style="height: 400px;">
				<table id="example1" class="table table-bordered table-striped " >
					<thead>
						<tr>
							<th>Image</th>
							<th>Deskripsi</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($gallery as $a)
						<tr> 
							<td><img src="{{asset('image/'.$a->image_path)}}" width="60px" height="40px"></td>

							<td>{{ $a->description }}</td>
							<td>
								<a href="
								{{route('education_tours.galleries.edit',['facility'=>$a->galleriable_id,'gallery'=>$a->id])}}">
								<button class="btn btn-warning">
									Edit
								</button>
							</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>

			{{ $gallery->links() }}
		</div>
	</div>
</div>
</div>
</section>
<section class="col-md-12">
	{{ $gallery->links() }}
</section>
</div>
@stop
@push('scripts')

<script src="{{asset('slick/jquery-2.2.0.min.js')}}" type="text/javascript"></script>
<script src="{{asset('slick/slick.js')}}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	$(document).on('ready', function() {
		$(".regular").slick({
			dots: false,
			infinite: true,
			slidesToShow: 4,
			slidesToScroll: 4
		});
	});
</script>
@endpush